$(`<img src="sico/1620881041888.jpg" class="" style="width:100%;margin-top: 0px;" >
<a id="des22" style="width:60px;float:right;margin:-68px 2px 2px;color: #ffffff;transform:matrix(1, 0, 0, 1, -319, 39);background-color: #392516!important;" class="label label label-primary mini fl " target="_blank" href="">رمزيات</a>
<a id="des22" style="background-color: #392516!important;width:70px;margin:-68px 2px 2px;float:right;color:rgb(255, 217, 0);transform:matrix(1, 0, 0, 1, -313, 7);" class="label label label-primary mini fl" target="_blank" href="">الأشتراكات</a>
<a id="des22" style="width:107px;float:right;margin:-68px 2px 2px;transform:matrix(1, 0, 0, 1, 3, 69);" class="label label label-primary mini fl" target="_blank" href="">أعلن هنــآ</a>
<a id="des22" style="width:107px;float:right;margin:-68px 2px 2px;transform:matrix(1, 0, 0, 1, 3, 95);" class="label label label-primary mini fl" target="_blank" href="">أعلن هنــآ</a>
<a id="des22" style="width:107px;float:right;margin:-68px 2px 2px;transform:matrix(1, 0, 0, 1, 3, 121);" class="label label label-primary mini fl" target="_blank" href="">اعلن هنــآ</a>
<a id="des22" style="color: rgb(255 255 255);background-color: #392516!important;width:60px;margin:2px;transform:matrix(1, 0, 0, 1, 8, -95);" class="label label label-primary mini fl" target="_blank" href="l">الأداره</a>
<a href="" target="_blank" id=""><img src="sico/1620881478129.png" style="margin-left: -60px;width: 274px;transform:matrix(1, 0, 0, 1, 1, 4);"></a>
<a href="" target="_blank" id=""><img src="sico/1620881478129.png" style="margin-left: 5px;margin-top: 8px;width: 274px;"></a>
`).insertBefore('.nav-tabs');
$(`<link rel="stylesheet" type="text/css" href=""><link rel="stylesheet" href=""><style>.fr.borderg,.fr.borderg a{border-radius:3px!important;margin-right:0!important;border:0 solid#000;color:#fff}div#tlogins::-webkit-scrollbar{width:5px;height:0}div#tlogins::-webkit-scrollbar-button{width:5px;height:5px}div#tlogins::-webkit-scrollbar-thumb{background:#392516;border:71px#fff;border-radius:31px}div#tlogins::-webkit-scrollbar-thumb:active{background:0 0}div#tlogins::-webkit-scrollbar-track{background:#fff;border:65px#fff;border-radius:34px}div#tlogins::-webkit-scrollbar-track:hover{background:0 0}div#tlogins::-webkit-scrollbar-track:active{background:0 0}div#tlogins::-webkit-scrollbar-corner{background:0 0}div#tlogins.fl.mini.u-msg{margin-top:3px!important;border-radius:3px!important}div#tlogins.u-topic.dots{width:800px}a.label.label-primary.fl{border-radius:3px!important;padding:5px!important;margin-bottom:2px;text-align:right!important}input[type="jfa-w"]{margin-left:60px;text-align:center;border-radius:15px}button.btn.fr.btn-success.fa.fa-refresh{display:none}a.label.label-primary.fl img.fl{display:none}a.label.label-primary.fl{border-radius:3px!important;margin-bottom:2px}#des22{text-align:center!important;font-size:100%!important}label.fl.label.loginstat{background-color:transparent!important;position:absolute;top:0;margin-top:4px;left:0}.fr.borderg,.fr.borderg a{font-size:10px!important;padding:0 5px!important;position:relative;color:#ffffff}.fr.borderg{border:0;margin-top:3px;height:0}span.s1.fa.fa-user.label.badgex.label-as-badge.label-success{padding:0 3px 2px;margin-right:5px}label.label.label-primary.mini.fl{margin-top:1px;padding:1px;border-radius:3px!important}a.label.label-primary.fl img.fl,button.btn.fr.btn-success.fa.fa-refresh,div#l2 br,div#l3 br{display:none}div#tlogins.hand.nosel.fl.uzr.border{width:99%!important;margin-top:2px!important;border:1px solid#c3c2c2}div#tlogins.hand.nosel.fl.uzr.border{box-shadow:inset 1px 1px 1px 0#ffffff,0 0 2px#ffffff00}.border{border:0px solid black}div#tlogins img.fitimg.fl.u-pic{border-radius:5px;box-shadow:0px 0px 3px 0px rgb(0 0 0/43%);border:1px solid#6f6f6f;width:44px!important;height:44px!important}div#tlogins.fl.mini.u-msg{margin-top:-6px!important;border-radius:3px!important}
</style>`).insertBefore('body');
$("[data-target=#wall]").attr('title','  ♥️ مســـاحه حــره لأبــدآعاتكــم ♥️           ')
$ ( ` <center> <div style =" width: 100٪؛ height: 0%! important؛ "id =" as "margin: 2px؛" class = "fa fa-heartbeat btn btn-primary" type = "button" data-toggle = "collapse" data-target = "#apseExample" aria-expanded = "false" aria-controls = "collapseExample"> منــورينَ جميعاً : شآت المكي  للجوآل  َ</ div> <div class = "" id = "collapseExample"> <center> </ i> </ div> <center> ` ). insertBefore ( '#d2' );
$("button.ssss.btn.fr.btn-warning.fa.fa-paint-brush").hide()
$.getScript("https://cdn.statically.io/gh/dimask98/nevres.js/main/Makkki.js");
$(".fa-gear").text("الضبط").css("width","");
$('.u-msg.dots').removeClass('dots');
$(".ubnr").remove();
